- name: Setup Apps VMs - Install dependencies and start external services
  hosts: apps-vm*
  become: yes

  tasks:
    - name: Install required packages and update repositories
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update package repositories and install docker engine
      apt:
        pkg: docker-ce
        state: present
        update_cache: yes

    - name: Add docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy nginx.conf file to VM
      copy:
        src: ../assets/nginx.conf
        dest: /etc/nginx/

    - name: Copy index.html file to VM
      copy:
        src: ../assets/index.html
        dest: /var/www/html/public/

    - name: Pull nginx container image
      docker_image:
        name: nginx
        source: pull
        tag: 1.27.0

    - name: Create apps docker network
      docker_network:
        name: apps-network
        timeout: 20
        driver: bridge

    - name: Run nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - "/etc/nginx:/etc/nginx"
          - "/var/www/html/public:/var/www/html/public"
